<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => '开心心理 | 专业抑郁心理咨询 Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '../send.php',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'jin@kajinhealth.com',
		'to' => 'jin@kajinhealth.com'
	),
	'fields' => array(
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email(必需)\' is required.',
				'format' => 'Field \'Email(必需)\' has an invalid email.'
			)
		),
		'custom_U2625' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '你在烦恼什么呢？',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'你在烦恼什么呢？\' is required.'
			)
		),
		'custom_U2629' => array(
			'order' => 4,
			'type' => 'string',
			'label' => '电话(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'电话(必需)\' is required.'
			)
		),
		'custom_U2634' => array(
			'order' => 3,
			'type' => 'string',
			'label' => '所在地/国码(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'所在地/国码(必需)\' is required.'
			)
		),
		'custom_U2639' => array(
			'order' => 6,
			'type' => 'string',
			'label' => '你从哪里知道我们(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'你从哪里知道我们(必需)\' is required.'
			)
		),
		'custom_U2644' => array(
			'order' => 5,
			'type' => 'radiogroup',
			'label' => '您的年龄',
			'required' => true,
			'optionItems' => array(
				'25 岁以下',
				'25 - 35 岁',
				'35 - 55 岁',
				'55 岁以上'
			),
			'errors' => array(
				'required' => 'Field \'您的年龄\' is required.',
				'format' => 'Field \'您的年龄\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
