<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => '幫親友詢問 Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '../send.php',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'jin@kajinhealth.com',
		'to' => 'jin@kajinhealth.com'
	),
	'fields' => array(
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email(必需)\' is required.',
				'format' => 'Field \'Email(必需)\' has an invalid email.'
			)
		),
		'custom_U193183' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '他的煩惱大概是什麼呢？',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'他的煩惱大概是什麼呢？\' is required.'
			)
		),
		'custom_U193174' => array(
			'order' => 4,
			'type' => 'string',
			'label' => '電話(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'電話(必需)\' is required.'
			)
		),
		'custom_U193191' => array(
			'order' => 3,
			'type' => 'string',
			'label' => '地區/國碼(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'地區/國碼(必需)\' is required.'
			)
		),
		'custom_U193179' => array(
			'order' => 6,
			'type' => 'string',
			'label' => '你從哪裡知道我們(必需)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'你從哪裡知道我們(必需)\' is required.'
			)
		),
		'custom_U193159' => array(
			'order' => 5,
			'type' => 'radiogroup',
			'label' => '您的年齡',
			'required' => true,
			'optionItems' => array(
				'25 歲以下',
				'25 - 35 歲',
				'35 - 55 歲',
				'55 歲以上'
			),
			'errors' => array(
				'required' => 'Field \'您的年齡\' is required.',
				'format' => 'Field \'您的年齡\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
