<?php
define('SORRY_NO_POST_MATCHED_YOUR_CRITERIA', __('Sorry, no posts matched your criteria.', 'one-page'));
define('GALLERY_AND_PORTFOLIO', __('Gallery and Portfolio', 'one-page'));
define('PORTFOLIO', __('Portfolio', 'one-page'));
define('SEARCH_FILTER_TAGS', __('Search Filter Tags', 'one-page'));
define('POPULAR_FILTER_TAGS', __('Popular Filter Tags', 'one-page'));
define('ALL_FILTER_TAGS', __('All Filter Tags', 'one-page'));
define('EDIT_FILTER_TAGS', __('Edit Filter Tags', 'one-page'));
define('UPDATE_FILTER_TAGS', __('Update Filter Tags', 'one-page'));
define('NEW_FILTER_TAGS_NAME', __('New Filter Tags Name', 'one-page'));
define('SEPARATE_FILTER_TAGS_WITH_CMMAS', __('Separate filter tags with commas', 'one-page'));
define('ADD_NEW_FILTER_TAGS', __('Add New Filter Tags', 'one-page'));
define('ADD_OR_REMOVE_FILTER_TAGS', __('Add or remove filter tags', 'one-page'));
define('CHOOSE_FROM_MOST_USED_FILTER_TAGS', __('Choose from the most used filter tags', 'one-page'));
define('FILTER', __('Filter', 'one-page'));
define('CATEGORIES', __('Categories', 'one-page'));
define('ARCHIVES', __('Archives', 'one-page'));
define('TITLE_COLON', __('Title:', 'one-page'));
define('NUMBER_OF_POSTS_TO_SHOW_COLON', __('Number of posts to show:', 'one-page'));
define('THIS_IS_SOMEWHAT', __('This is somewhat embarrassing, isn&rsquo;t it?', 'one-page'));
define('IT_SEEMS_WE', __('It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching can help.', 'one-page'));
define('TRY_LOOKING_IN_MONTHLY_ARCHIVES', __('Try looking in the monthly archives. %1$s', 'one-page'));
define('READ_MORE', __('Read More', 'one-page'));
define('PRIMARY_WIDGET', __('Primary Widget Area', 'one-page'));
define('THE_PRIMARY_WIDGET', __('The primary widget area', 'one-page'));
define('SECONDRY_WIDGET', __('Secondary Widget Area', 'one-page'));
define('THE_SECONDRY_WIDGET', __('The secondary widget area', 'one-page'));
define('FIRST_FOOTER_WIDGET', __('First Footer Widget Area', 'one-page'));
define('THE_FIRST_FOOTER_WIDGET', __('The first footer widget area', 'one-page'));
define('SECONDRY_FOOTER_WIDGET', __('Second Footer Widget Area', 'one-page'));
define('THE_SECONDRY_FOOTER_WIDGET', __('The second footer widget area', 'one-page'));
define('THIRD_FOOTER_WIDGET', __('Third Footer Widget Area', 'one-page'));
define('THE_THIRD_FOOTER_WIDGET', __('The third footer widget area', 'one-page'));
define('FOURTH_FOOTER_WIDGET', __('Fourth Footer Widget Area', 'one-page'));
define('THE_FOURTH_FOOTER_WIDGET', __('The fourth footer widget area', 'one-page'));
define('HOME_TEXT', __('Home', 'one-page'));
define('MOST_USED_CATEGORIES', __('Most used categories', 'one-page'));
define('BOOKMARK_THE', __('Bookmark the', 'one-page'));
define('PERMALINK', __('&nbsp;permalink', 'one-page'));
define('NEWER_POST', __('Newer posts &rarr;', 'one-page'));
define('OLDER_POST', __('&larr; Older posts', 'one-page'));
define('NOTHING_FOUND', __('Nothing Found', 'one-page'));
define('SORRY_NOTHING_FOUND_TRY_AGAIN_WITH_ANOTHER_KEYWORD', __('Sorry, but nothing matched your search criteria. Please try again with some different keywords.', 'one-page'));
define('SEARCH_RESULTS_FOR', __('Search Results for: %s', 'one-page'));
define('TAG_ARCHIVES', __('Tag Archives: %s', 'one-page'));
define('AUTHOR_ARCHIVES', __('Author Archives: %s', 'one-page'));
define('ABOUT_AUTHOR', __('About %s', 'one-page'));
define('DAILY_ARCHIVES', __('Daily Archives: %s', 'one-page'));
define('MONTHLY_ARCHIVES', __('Monthly Archives: %s', 'one-page'));
define('YEARLY_ARCHIVES', __('Yearly Archives: %s', 'one-page'));
define('BLOG_ARCHIVES', __('Blog Archives', 'one-page'));
define('MAIN_MENU', __('Main Menu', 'one-page'));
define('RETURN_TO_S', __('Return to %s', 'one-page'));
define('BY_AUTHOR', __('By %2$s', 'one-page'));
define('VIEW_ALL_POST_BY', __('View all posts by %s', 'one-page'));
define('PUBLISHED_IN_TIME', __('Published %2$s', 'one-page'));
define('FULL_SIZE_IS', __('Full size is %s pixels', 'one-page'));
define('LINK_TO_FULL_SIZE_IMAGE', __('Link to full-size image', 'one-page'));
define('EDIT', __('Edit', 'one-page'));
define('PAGES_COLON', __('Pages:', 'one-page'));
define('CATEGORY_ARCHIVES', __('Category Archives: %s', 'one-page'));
define('PAGE', __('Page', 'one-page'));
?>